### ISSUE TITLE
Extract api_error_message from HTTP 4XX responses

### ISSUE THREAD

**Issue by cccs-mk** [CybercentreCanada/assemblyline-java-client#21]
Currently, `AssemblylineClient` extracts the `api_error_message` field from the JSON response for 5XX responses. It does not extract the error message for 4XX responses. It seems like the client _should_ be extracting messages for 4XX responses to make debugging easier.

I have seen at least one example where a `400 BAD REQUEST` response body had a message that would have been useful:
```json
{
  "api_error_message":"You cannot start a scan with higher classification then you're allowed to see",
  "api_response":{},
  "api_server_version":"4.0.0",
  "api_status_code":400
}
```
The error generated by the client for this response was:
```
WebClientResponseException$BadRequest: 400 Bad Request from POST https://malware.cyber.gc.ca/api/v4/submit/
```
Instead, it would have been nice to get:
```
WebClientResponseException$BadRequest: 400 Bad Request : You cannot start a scan with higher classification then you're allowed to see from POST https://malware.cyber.gc.ca/api/v4/submit/
```
(This is the same formatting used for 5XX errors.)

**Comment by cccs-mk** [comment]
Extracting errors from both 4XX and 5XX seems to be safe (I was worried that modifying the 4XX errors would cause issues somewhere else). The only minor hiccup is that the test cases for logging in don't include a bodies for their mock 401 UNAUTHORIZED responses, which means that attempting to read the message throws an error. That part is easily fixable, but there is one test case that seems tricky: [testIsSubmissionCompleteUnauthorizedTwice](https://github.com/CybercentreCanada/assemblyline-java-client/blob/0badd1ce40f8680dbb8db678a9199fcdddd24ba8/src/test/java/ca/gc/cyber/ops/assemblyline/java/client/clients/AssemblylineClientTest.java#L317).

My understanding is that the test is trying simulate a case where a login fails (non-existent user, wrong API key, etc). From what I understand, the sequence of events in the client would be approximately:
1. Initial request fails because session token is not included in request.
2. Before retying, attempt to log in.
3. Retry initial request.

Given that sequence of events, I would expect the mock responses to be:
1. 401 (Session Rejected)
2. 401 (non-existent user, invalid API key, etc)
3. 401 (Session Rejected)

However, ordering the responses as described above does not work and the "correct" ordering of responses is:
1. 401
2. 200 (Successful login)
3. 401

Even though I can see how the current mocks produce the expected result, I don't understand what situation they are simulating.

**Comment by cpmccle** [comment]
This test was written to test that the Retry.max(1) worked and would stop after that. I can see that the test itself does not make much sense though as you are correct and the situation would never rise. The test can be removed I believe.  

As well, I agree it makes sense to add the 400 error messages.

**Comment by cccs-mk** [comment]
I'll change the test (or replace it) so that it verifies that a failed login attempt via the retry mechanism propagates a useful message back to the user (e.g. Invalid API key).
